// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: pb/unixfs.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Liuguang.Storage.Pb {

  /// <summary>Holder for reflection information generated from pb/unixfs.proto</summary>
  public static partial class UnixfsReflection {

    #region Descriptor
    /// <summary>File descriptor for pb/unixfs.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static UnixfsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg9wYi91bml4ZnMucHJvdG8SDHVuaXhmcy52MS5wYiLfAQoERGF0YRIpCgRU",
            "eXBlGAEgAigOMhsudW5peGZzLnYxLnBiLkRhdGEuRGF0YVR5cGUSDAoERGF0",
            "YRgCIAEoDBIQCghmaWxlc2l6ZRgDIAEoBBISCgpibG9ja3NpemVzGAQgAygE",
            "EhAKCGhhc2hUeXBlGAUgASgEEg4KBmZhbm91dBgGIAEoBCJWCghEYXRhVHlw",
            "ZRIHCgNSYXcQABINCglEaXJlY3RvcnkQARIICgRGaWxlEAISDAoITWV0YWRh",
            "dGEQAxILCgdTeW1saW5rEAQSDQoJSEFNVFNoYXJkEAUiHAoITWV0YWRhdGES",
            "EAoITWltZVR5cGUYASABKAlCFqoCE0xpdWd1YW5nLlN0b3JhZ2UuUGI="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Liuguang.Storage.Pb.Data), global::Liuguang.Storage.Pb.Data.Parser, new[]{ "Type", "Data_", "Filesize", "Blocksizes", "HashType", "Fanout" }, null, new[]{ typeof(global::Liuguang.Storage.Pb.Data.Types.DataType) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Liuguang.Storage.Pb.Metadata), global::Liuguang.Storage.Pb.Metadata.Parser, new[]{ "MimeType" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Data : pb::IMessage<Data>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Data> _parser = new pb::MessageParser<Data>(() => new Data());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Data> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Liuguang.Storage.Pb.UnixfsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Data() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Data(Data other) : this() {
      _hasBits0 = other._hasBits0;
      type_ = other.type_;
      data_ = other.data_;
      filesize_ = other.filesize_;
      blocksizes_ = other.blocksizes_.Clone();
      hashType_ = other.hashType_;
      fanout_ = other.fanout_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Data Clone() {
      return new Data(this);
    }

    /// <summary>Field number for the "Type" field.</summary>
    public const int TypeFieldNumber = 1;
    private readonly static global::Liuguang.Storage.Pb.Data.Types.DataType TypeDefaultValue = global::Liuguang.Storage.Pb.Data.Types.DataType.Raw;

    private global::Liuguang.Storage.Pb.Data.Types.DataType type_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Liuguang.Storage.Pb.Data.Types.DataType Type {
      get { if ((_hasBits0 & 1) != 0) { return type_; } else { return TypeDefaultValue; } }
      set {
        _hasBits0 |= 1;
        type_ = value;
      }
    }
    /// <summary>Gets whether the "Type" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasType {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "Type" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearType() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "Data" field.</summary>
    public const int Data_FieldNumber = 2;
    private readonly static pb::ByteString Data_DefaultValue = pb::ByteString.Empty;

    private pb::ByteString data_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString Data_ {
      get { return data_ ?? Data_DefaultValue; }
      set {
        data_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "Data" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasData_ {
      get { return data_ != null; }
    }
    /// <summary>Clears the value of the "Data" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearData_() {
      data_ = null;
    }

    /// <summary>Field number for the "filesize" field.</summary>
    public const int FilesizeFieldNumber = 3;
    private readonly static ulong FilesizeDefaultValue = 0UL;

    private ulong filesize_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong Filesize {
      get { if ((_hasBits0 & 2) != 0) { return filesize_; } else { return FilesizeDefaultValue; } }
      set {
        _hasBits0 |= 2;
        filesize_ = value;
      }
    }
    /// <summary>Gets whether the "filesize" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasFilesize {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "filesize" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearFilesize() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "blocksizes" field.</summary>
    public const int BlocksizesFieldNumber = 4;
    private static readonly pb::FieldCodec<ulong> _repeated_blocksizes_codec
        = pb::FieldCodec.ForUInt64(32);
    private readonly pbc::RepeatedField<ulong> blocksizes_ = new pbc::RepeatedField<ulong>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<ulong> Blocksizes {
      get { return blocksizes_; }
    }

    /// <summary>Field number for the "hashType" field.</summary>
    public const int HashTypeFieldNumber = 5;
    private readonly static ulong HashTypeDefaultValue = 0UL;

    private ulong hashType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong HashType {
      get { if ((_hasBits0 & 4) != 0) { return hashType_; } else { return HashTypeDefaultValue; } }
      set {
        _hasBits0 |= 4;
        hashType_ = value;
      }
    }
    /// <summary>Gets whether the "hashType" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasHashType {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "hashType" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearHashType() {
      _hasBits0 &= ~4;
    }

    /// <summary>Field number for the "fanout" field.</summary>
    public const int FanoutFieldNumber = 6;
    private readonly static ulong FanoutDefaultValue = 0UL;

    private ulong fanout_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong Fanout {
      get { if ((_hasBits0 & 8) != 0) { return fanout_; } else { return FanoutDefaultValue; } }
      set {
        _hasBits0 |= 8;
        fanout_ = value;
      }
    }
    /// <summary>Gets whether the "fanout" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasFanout {
      get { return (_hasBits0 & 8) != 0; }
    }
    /// <summary>Clears the value of the "fanout" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearFanout() {
      _hasBits0 &= ~8;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Data);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Data other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (Data_ != other.Data_) return false;
      if (Filesize != other.Filesize) return false;
      if(!blocksizes_.Equals(other.blocksizes_)) return false;
      if (HashType != other.HashType) return false;
      if (Fanout != other.Fanout) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasType) hash ^= Type.GetHashCode();
      if (HasData_) hash ^= Data_.GetHashCode();
      if (HasFilesize) hash ^= Filesize.GetHashCode();
      hash ^= blocksizes_.GetHashCode();
      if (HasHashType) hash ^= HashType.GetHashCode();
      if (HasFanout) hash ^= Fanout.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasType) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (HasData_) {
        output.WriteRawTag(18);
        output.WriteBytes(Data_);
      }
      if (HasFilesize) {
        output.WriteRawTag(24);
        output.WriteUInt64(Filesize);
      }
      blocksizes_.WriteTo(output, _repeated_blocksizes_codec);
      if (HasHashType) {
        output.WriteRawTag(40);
        output.WriteUInt64(HashType);
      }
      if (HasFanout) {
        output.WriteRawTag(48);
        output.WriteUInt64(Fanout);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasType) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (HasData_) {
        output.WriteRawTag(18);
        output.WriteBytes(Data_);
      }
      if (HasFilesize) {
        output.WriteRawTag(24);
        output.WriteUInt64(Filesize);
      }
      blocksizes_.WriteTo(ref output, _repeated_blocksizes_codec);
      if (HasHashType) {
        output.WriteRawTag(40);
        output.WriteUInt64(HashType);
      }
      if (HasFanout) {
        output.WriteRawTag(48);
        output.WriteUInt64(Fanout);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasType) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (HasData_) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Data_);
      }
      if (HasFilesize) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Filesize);
      }
      size += blocksizes_.CalculateSize(_repeated_blocksizes_codec);
      if (HasHashType) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(HashType);
      }
      if (HasFanout) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Fanout);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Data other) {
      if (other == null) {
        return;
      }
      if (other.HasType) {
        Type = other.Type;
      }
      if (other.HasData_) {
        Data_ = other.Data_;
      }
      if (other.HasFilesize) {
        Filesize = other.Filesize;
      }
      blocksizes_.Add(other.blocksizes_);
      if (other.HasHashType) {
        HashType = other.HashType;
      }
      if (other.HasFanout) {
        Fanout = other.Fanout;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::Liuguang.Storage.Pb.Data.Types.DataType) input.ReadEnum();
            break;
          }
          case 18: {
            Data_ = input.ReadBytes();
            break;
          }
          case 24: {
            Filesize = input.ReadUInt64();
            break;
          }
          case 34:
          case 32: {
            blocksizes_.AddEntriesFrom(input, _repeated_blocksizes_codec);
            break;
          }
          case 40: {
            HashType = input.ReadUInt64();
            break;
          }
          case 48: {
            Fanout = input.ReadUInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Type = (global::Liuguang.Storage.Pb.Data.Types.DataType) input.ReadEnum();
            break;
          }
          case 18: {
            Data_ = input.ReadBytes();
            break;
          }
          case 24: {
            Filesize = input.ReadUInt64();
            break;
          }
          case 34:
          case 32: {
            blocksizes_.AddEntriesFrom(ref input, _repeated_blocksizes_codec);
            break;
          }
          case 40: {
            HashType = input.ReadUInt64();
            break;
          }
          case 48: {
            Fanout = input.ReadUInt64();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the Data message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum DataType {
        [pbr::OriginalName("Raw")] Raw = 0,
        [pbr::OriginalName("Directory")] Directory = 1,
        [pbr::OriginalName("File")] File = 2,
        [pbr::OriginalName("Metadata")] Metadata = 3,
        [pbr::OriginalName("Symlink")] Symlink = 4,
        [pbr::OriginalName("HAMTShard")] Hamtshard = 5,
      }

    }
    #endregion

  }

  public sealed partial class Metadata : pb::IMessage<Metadata>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Metadata> _parser = new pb::MessageParser<Metadata>(() => new Metadata());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Metadata> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Liuguang.Storage.Pb.UnixfsReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Metadata() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Metadata(Metadata other) : this() {
      mimeType_ = other.mimeType_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Metadata Clone() {
      return new Metadata(this);
    }

    /// <summary>Field number for the "MimeType" field.</summary>
    public const int MimeTypeFieldNumber = 1;
    private readonly static string MimeTypeDefaultValue = "";

    private string mimeType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string MimeType {
      get { return mimeType_ ?? MimeTypeDefaultValue; }
      set {
        mimeType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "MimeType" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasMimeType {
      get { return mimeType_ != null; }
    }
    /// <summary>Clears the value of the "MimeType" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearMimeType() {
      mimeType_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Metadata);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Metadata other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MimeType != other.MimeType) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasMimeType) hash ^= MimeType.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasMimeType) {
        output.WriteRawTag(10);
        output.WriteString(MimeType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasMimeType) {
        output.WriteRawTag(10);
        output.WriteString(MimeType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasMimeType) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MimeType);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Metadata other) {
      if (other == null) {
        return;
      }
      if (other.HasMimeType) {
        MimeType = other.MimeType;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            MimeType = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            MimeType = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
